RainBase.Logging.Info("Loading RainBase client side modules...")
RainBase.Util.IncludeDir("rainbase/modules/client", function(lua)
    RainBase.Logging.Info("Loading ", lua)
end)
RainBase.Logging.Info("RainBase client side modules loaded.")